# Generated by Django 4.1.3 on 2022-12-07 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_room_uploadfile_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='file',
            new_name='document',
        ),
    ]
