# Generated by Django 4.1.3 on 2022-12-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_file_uploadfile_document'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFile',
            new_name='Document',
        ),
    ]
