# Generated by Django 4.1.3 on 2022-12-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prj_title', models.CharField(max_length=200)),
                ('prj_detail', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='')),
            ],
        ),
    ]
