# Generated by Django 4.1.3 on 2022-12-10 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_remove_document_prj_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Registerinfo',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='SignUpForm',
        ),
    ]
