# Generated by Django 4.1.3 on 2022-12-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0011_delete_document_delete_message_delete_registerinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('password1', models.CharField(max_length=1000)),
                ('password2', models.CharField(max_length=1000)),
                ('us', models.CharField(max_length=100)),
            ],
        ),
    ]
