# Generated by Django 4.1.3 on 2022-12-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=1000)),
                ('last_name', models.CharField(max_length=1000)),
                ('dob', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=1000)),
                ('mail', models.CharField(max_length=1000)),
                ('mobile_number', models.CharField(max_length=1000)),
                ('course', models.CharField(max_length=1000)),
            ],
        ),
    ]
