# Generated by Django 4.1.3 on 2022-12-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_registerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaverequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('TO', models.CharField(max_length=1000)),
                ('Date', models.CharField(max_length=1000)),
                ('Reason', models.CharField(max_length=10000)),
            ],
        ),
    ]
